//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marbal.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarbalEntities : DbContext
    {
        public MarbalEntities()
            : base("name=MarbalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmountTypeTbl> AmountTypeTbls { get; set; }
        public virtual DbSet<CategoryTbl> CategoryTbls { get; set; }
        public virtual DbSet<ExpenseTbl> ExpenseTbls { get; set; }
        public virtual DbSet<ExpenseTypeTbl> ExpenseTypeTbls { get; set; }
        public virtual DbSet<GatePassDetailTbl> GatePassDetailTbls { get; set; }
        public virtual DbSet<GatePassTbl> GatePassTbls { get; set; }
        public virtual DbSet<OrderBookDetailTbl> OrderBookDetailTbls { get; set; }
        public virtual DbSet<OrderBookTbl> OrderBookTbls { get; set; }
        public virtual DbSet<OrderTransectionTbl> OrderTransectionTbls { get; set; }
        public virtual DbSet<ProductCategoryTbl> ProductCategoryTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<RecordTruckTbl> RecordTruckTbls { get; set; }
        public virtual DbSet<SupplierTbl> SupplierTbls { get; set; }
        public virtual DbSet<SupplierTransectionTbl> SupplierTransectionTbls { get; set; }
        public virtual DbSet<SupplierTruckTran> SupplierTruckTrans { get; set; }
        public virtual DbSet<TruckDetailTbl> TruckDetailTbls { get; set; }
        public virtual DbSet<vw_CategoriesByProduct> vw_CategoriesByProduct { get; set; }
        public virtual DbSet<vw_ExpensesTbl> vw_ExpensesTbl { get; set; }
        public virtual DbSet<vw_ProductTbl> vw_ProductTbl { get; set; }
        public virtual DbSet<vw_TruckDetailTbl> vw_TruckDetailTbl { get; set; }
    }
}
