//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marbal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategoryTbl()
        {
            this.OrderBookDetailTbls = new HashSet<OrderBookDetailTbl>();
            this.TruckDetailTbls = new HashSet<TruckDetailTbl>();
        }
    
        public int ProductCatID { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBookDetailTbl> OrderBookDetailTbls { get; set; }
        public virtual ProductTbl ProductTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckDetailTbl> TruckDetailTbls { get; set; }
    }
}
