//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marbal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTruckTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordTruckTbl()
        {
            this.SupplierTruckTrans = new HashSet<SupplierTruckTran>();
            this.TruckDetailTbls = new HashSet<TruckDetailTbl>();
        }
    
        public int ID { get; set; }
        public string DriverName { get; set; }
        public string DrivrNumber { get; set; }
        public string TruckNumber { get; set; }
        public Nullable<int> TruckWeight { get; set; }
        public Nullable<int> PerTonRent { get; set; }
        public Nullable<int> LabourCost { get; set; }
        public Nullable<int> WeightExpense { get; set; }
        public Nullable<int> TotalSqFeet { get; set; }
        public Nullable<int> InAdvancePament { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual SupplierTbl SupplierTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierTruckTran> SupplierTruckTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckDetailTbl> TruckDetailTbls { get; set; }
    }
}
