//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marbal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTransectionTbl
    {
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Detail { get; set; }
        public Nullable<int> SubmitAmount { get; set; }
        public Nullable<int> AmountType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual SupplierTbl SupplierTbl { get; set; }
        public virtual SupplierTruckTran SupplierTruckTran { get; set; }
    }
}
